language: csharp
mono: none
dotnet: 2.0.0

branches:
  only:
  - master
  - staging
  - production

install:
- dotnet restore

script:
 - dotnet build

 deploy:
  provider: script
  script: bash scripts/deploy.sh
